# LSP
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'thomasfaingnaert/vim-lsp-snippets'

[[plugins]]
repo = 'thomasfaingnaert/vim-lsp-ultisnips'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'

# git
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
"" git操作
    nnoremap g[ :GitGutterPrevHunk<CR>
    nnoremap g] :GitGutterNextHunk<CR>
    nnoremap gh :GitGutterLineHighlightsToggle<CR>
    nnoremap gp :GitGutterPreviewHunk<CR>
    highlight GitGutterAdd ctermfg=green
    highlight GitGutterChange ctermfg=blue
    highlight GitGutterDelete ctermfg=red
    set updatetime=250
'''

# vim-airline dependency
[[plugins]]
repo = 'tpope/vim-fugitive'

# vim-airline dependency
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
        let g:airline_theme = 'badwolf'
'''
# vim-airline
[[plugins]]
repo = 'vim-airline/vim-airline'
depends =['vim-fugitive', 'vim-airline-themes']
hook_add = '''
        let g:airline_powerline_fonts = 1
        let g:airline#extensions#tabline#enabled = 1
        let g:airline#extensions#tabline#buffer_nr_show = 1
        let g:airline#extensions#branch#enabled=1
        let g:airline#extensions#hunks#enabled=0
        if !exists('g:airline_symbols')
                let g:airline_symbols = {}
        endif
        let g:airline_section_a = airline#section#create(['mode', 'crypt'])
'''

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
hook_add = '''
  let g:fern#renderer = 'nerdfont'
'''

[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'
hook_add = '''
  augroup my-glyph-palette
    autocmd! *
    autocmd FileType fern call glyph_palette#apply()
    autocmd FileType nerdtree,startify call glyph_palette#apply()
  augroup END
'''

[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
        let g:fern#default_hidden=1
        let g:fern#renderer = 'nerdfont'
        nnoremap <C-n> :Fern . -reveal=% -drawer -toggle -width=40<CR>
'''

[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add = '''
        nnoremap <C-/> :TComment<CR>
        vnoremap <C-/> :'<.'>TComment<CR>
'''

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''
        let g:rainbow_active = 1
'''

[[plugins]]
repo = 'sainnhe/gruvbox-material'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
        nnoremap s <Plug>(easymotion-overwin-f2)
'''

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

# fzf
[[plugins]]
repo = 'junegunn/fzf'
hook_post_update = './install --all'
merged = '0'

# fzf.vim
[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
    command! -bang -nargs=* Rg
    \ call fzf#vim#grep(
    \ 'rg --column --line-number --hidden --ignore-case --no-heading --color=always '.shellescape(<q-args>), 1,
    \ <bang>0 ? fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'up:60%')
    \ : fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'right:50%:hidden', '?'),
    \ <bang>0)
    nnoremap <silent> ,r :Rg<CR>
    nnoremap <silent> ,f :GFiles<CR>
    nnoremap <silent> ,F :GFiles?<CR>
    nnoremap <silent> ,b :Buffers<CR>
    nnoremap <silent> ,l :BLines<CR>
    nnoremap <silent> ,h :History<CR>
'''

# markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'previm/previm'
hook_add = '''
    autocmd BufRead,BufNewFile *.md  set filetype=markdown
    let g:vim_markdown_folding_disabled=1
    let g:previm_enable_realtime=1
'''

[[plugins]]
repo = 'tyru/open-browser.vim'

# golang
[[plugins]]
repo = 'mattn/vim-goimports'
hook_add = '''
    let g:goimports = 1
'''
